name: travel_planner
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # Icons for iOS
  cupertino_icons: ^1.0.8
  
  # Backend
  supabase_flutter: ^2.12.0
  
  # --- NEW MAP FEATURES ---
  flutter_map: ^6.0.0       # The Free Map (OpenStreetMap)
  latlong2: ^0.9.0          # Helper for Coordinates
  url_launcher: ^6.3.2      # Opens Google Maps for Directions
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  http: ^1.1.0
  intl: ^0.18.1
  flutter_speed_dial: ^7.0.0
  table_calendar: ^3.0.9
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # 👇 ADD THIS LINE 👇
  flutter_launcher_icons: ^0.13.1 

flutter:
  uses-material-design: true

  # Your Images
  assets:
    - assets/lakbay.png

# 👇 ADD THIS ENTIRE SECTION AT THE BOTTOM 👇
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/lakbay.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/lakbay.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"